A <%= @exception.class %> occurred <%= ExceptionNotifier.exception_source(@controller) %>:

  <%= @exception.message %>
  <%= @backtrace.first %>

<%= @sections.map { |section| render_section(section) }.join %>
